### ISSUE TITLE
Add endpoints for speeches in plenary session

### ISSUE THREAD

**Issue by JabobKrauskopf** [open-discourse/open-discourse#105]
Add two new endpoints to the express service

- Get all plenary session ids
- Get all speeches given plenary session id

This will be used for SEO improvements for [opendiscourse.de](https://opendiscourse.de/)

**Comment by OFranke** [comment]
@JabobKrauskopf 
I am working on displaying the protocols directly in the frontend, can you also add the `electoralTerm` and `session` to the endpoint for full text search at https://github.com/open-discourse/open-discourse/blob/f7d47803778126aae8bb25c8bfbe0d028acd02ed/proxy/src/index.ts#L81 ?

Then I can link from full text search results to the protocol on opendiscourse.de instead of the original PDF document hosted at bundestag.
