### ISSUE TITLE
[BUG REPORT]Systematic missing of interjections from AfD 

### ISSUE THREAD

**Issue by LiRako** [open-discourse/open-discourse#141]
**Describe the bug**
When looking into the interjection patterns of the different parties in the Bundestag in the last two legislation periods (19,20), I noticed that for the AfD only those interjections appear in the dataset that are linked to a specific politician. 
This means that while for every other party there are multiple instances of interjections (be it "Beifall" or any other type) that are only linked to the interjecting party, this is not the case for interjections coming from the AfD. This results in a much lower total of interjections overall coming from AfD and a systematic bias. 

Why is it that general interjections from the AfD party (without reference to a specific politician) are systematically missing? 
Is there a way to fix this problem?  

I would very much appreciate any kind of tips or help. 
Thanks in advance!

**Comment by JabobKrauskopf** [comment]
Thanks for the report!

The main codebase was written with a focus on the 1st to 18th election period when the AfD was not in the Bundestag.
We seem to have missed to add the AfD to the parties list when adding support for the 19th election period.
This should be an easy fix by just adding a pattern for the AfD to the parties dictionary here: https://github.com/open-discourse/open-discourse/blob/develop/python/src/od_lib/helper_functions/extract_contributions.py#L6-L29

However creating an updated dataset/database might be difficult atm because of other issues (see #138) and changes to the Bundestags' API.
